modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="anal_craft"
version="1.0.0"
displayName="Anal Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nikita, MCreator"

[[dependencies.anal_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




