/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.analcraft;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class AnalCraftModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public AnalCraftModElements() {
		sounds.put(new ResourceLocation("anal_craft", "leather"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "leather")));
		sounds.put(new ResourceLocation("anal_craft", "agh"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "agh")));
		sounds.put(new ResourceLocation("anal_craft", "aghh"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "aghh")));
		sounds.put(new ResourceLocation("anal_craft", "aaaaaaa"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "aaaaaaa")));
		sounds.put(new ResourceLocation("anal_craft", "ahr"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "ahr")));
		sounds.put(new ResourceLocation("anal_craft", "bondage"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "bondage")));
		sounds.put(new ResourceLocation("anal_craft", "assclap"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "assclap")));
		sounds.put(new ResourceLocation("anal_craft", "oficeri"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "oficeri")));
		sounds.put(new ResourceLocation("anal_craft", "feelgood"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "feelgood")));
		sounds.put(new ResourceLocation("anal_craft", "notrdam"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "notrdam")));
		sounds.put(new ResourceLocation("anal_craft", "zozh"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "zozh")));
		sounds.put(new ResourceLocation("anal_craft", "bremenskiemuzicanti"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "bremenskiemuzicanti")));
		sounds.put(new ResourceLocation("anal_craft", "kozhanyjtraktor"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "kozhanyjtraktor")));
		sounds.put(new ResourceLocation("anal_craft", "motilek"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "motilek")));
		sounds.put(new ResourceLocation("anal_craft", "valim"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "valim")));
		sounds.put(new ResourceLocation("anal_craft", "esaul"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "esaul")));
		sounds.put(new ResourceLocation("anal_craft", "zagulyal"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "zagulyal")));
		sounds.put(new ResourceLocation("anal_craft", "bomj"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "bomj")));
		sounds.put(new ResourceLocation("anal_craft", "yunostvsapogah"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "yunostvsapogah")));
		sounds.put(new ResourceLocation("anal_craft", "ibelieve"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "ibelieve")));
		sounds.put(new ResourceLocation("anal_craft", "portalactivate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "portalactivate")));
		sounds.put(new ResourceLocation("anal_craft", "fisting"), new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "fisting")));
		sounds.put(new ResourceLocation("anal_craft", "swallowmycum"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "swallowmycum")));
		sounds.put(new ResourceLocation("anal_craft", "thankyousir"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "thankyousir")));
		sounds.put(new ResourceLocation("anal_craft", "oxsuckmiron"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "oxsuckmiron")));
		sounds.put(new ResourceLocation("anal_craft", "gachimuch"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "gachimuch")));
		sounds.put(new ResourceLocation("anal_craft", "marionetka"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("anal_craft", "marionetka")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("anal_craft").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == AnalCraftModElements.ModElement.class)
						elements.add((AnalCraftModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(AnalCraftModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		AnalCraftMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final AnalCraftModElements elements;
		protected final int sortid;
		public ModElement(AnalCraftModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
